# Generated by Django 5.2.6 on 2026-10-03 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_workschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('work_type', models.CharField(choices=[('TASK', 'Task'), ('MEETING', 'Meeting'), ('ROUTINE', 'Routine'), ('SUPPORT', 'Support'), ('TRAINING', 'Training'), ('PROJECT', 'Project'), ('INCIDENT', 'Incident'), ('OTHER', 'Other')], default='TASK', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('DEFERRED', 'Deferred'), ('CANCELLED', 'Cancelled'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('planned_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='companies.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='companies.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_work_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
