# Generated by Django 5.2.6 on 2026-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_outcome_created_at_alter_outcome_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='executions',
            field=models.ManyToManyField(blank=True, related_name='outcomes', to='companies.workexecution'),
        ),
    ]
